file(REMOVE "${SAVE}" "${SAVE}.pending" "${SAVE}.lock")
execute_process(COMMAND "${SPEC}" write "${SAVE}" RESULT_VARIABLE written)
if(NOT written EQUAL 0)
    message(FATAL_ERROR "HOME writer process failed: ${written}")
endif()
execute_process(COMMAND "${SPEC}" read "${SAVE}" RESULT_VARIABLE restored)
if(NOT restored EQUAL 0)
    message(FATAL_ERROR "Fresh HOME reader process failed: ${restored}")
endif()
file(REMOVE "${SAVE}" "${SAVE}.pending" "${SAVE}.lock")
